### ISSUE TITLE
[BUG] Fix config.py using module definition that no longer exists

### ISSUE THREAD

**Issue by LucientZ** [LucientZ/DiscordPyBot#38]
When running `make config` the following error gets thrown:
```bash
python3 ./src/config.py
Traceback (most recent call last):
  File "/home/usr/DSIBB/DiscordPyBot/./src/config.py", line 180, in <module>
    main()
  File "/home/usr/DSIBB/DiscordPyBot/./src/config.py", line 153, in main
    dt.init_guild_config()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'datahandling' has no attribute 'init_guild_config'
make: *** [makefile:11: config] Error 1
```

**Comment by LucientZ** [comment]
Fixed with commit c564e0ab7189b5cdd069925aff977b352570d939

init_guild_config() used to be in datahandling.py and was undefined after changing how guild config is handled. Seeing if config.py can run should have been part of the unit tests.
